name: Build and push

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  executron:
    name: Build and push executron
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_REGISTRY_LOGIN }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build executron
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          tags: |
            twirapp/executron:latest
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

  executron-node:
    name: Build and push node
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_REGISTRY_LOGIN }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build executron
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          tags: |
            twirapp/executron:node-latest
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: ./images/node/Dockerfile